### ISSUE TITLE
Plugin does not load

### ISSUE THREAD

**Issue by THXPGit** [PlayerMiller109/obsidian-sheets-basic#1]
Manually installing the plugin allows it to be shown in the plugins window, but makes it impossible to enable. When attempting to enable, I am met with a "failed to load plugin" error. The issue persists through Windows 10 and 11, as well as when using source code and compiled code.

**Comment by PlayerMiller109** [comment]
Hi, what kind of manually installing? Just download to test and everything's normal on my side. Win11 Obsidian v1.6.7 Sandbox Vault.

**Comment by THXPGit** [comment]
I've tested both extracting the sheets-basic.zip file into the plugins folder as well as downloading the main.js and manifest.js files and placing them into a new sheets-basic folder. Both methods allow it to appear in the plugin window but both receive an error when clicking the "enable" toggle.

**Comment by PlayerMiller109** [comment]
That's kind of weird. What are your Obsidian Current and Installer versions? Maybe test it in Sandbox Vault?

Here is my test GIF, downloaded and enabled:

<img width="500" src="https://github.com/user-attachments/assets/dfd54779-cad0-4d1b-bcd1-9ddc817ec2b3">

**Comment by THXPGit** [comment]
Solved it. The plugin displays the error text if you have the original sheets expanded in the plugin vault.
