### ISSUE TITLE
阅读模式下，表格中的图像无法显示

### ISSUE THREAD

**Issue by tai-jing-jian** [PlayerMiller109/obsidian-sheets-basic#2]
编辑模式下，图片能正常显示。切到阅读模式下，图片就没了

**Comment by PlayerMiller109** [comment]
Win11 v1.6.7 沙箱未复现。请沙箱测试排查是否存在插件主题 CSS 冲突、附必要截图及源码模式文本（用代码块格式包裹）。

**Comment by tai-jing-jian** [comment]
未使用其他css，默认主题
![20241016131820](https://github.com/user-attachments/assets/6da430c4-c971-4b5d-af05-5dfb96586a01)
![20241016131831](https://github.com/user-attachments/assets/fff3ec09-379c-45c2-bbf1-206a0fa191bf)
只开一个插件，图片阅读模式下，未显示，
![20241016132018](https://github.com/user-attachments/assets/9674f18b-74ec-408f-b964-1754a3b630e2)
![20241016132021](https://github.com/user-attachments/assets/80dbd871-86be-4869-a686-8005f1544364)
未开插件，正常
![5](https://github.com/user-attachments/assets/41dea499-ae47-41a3-95a4-aee0052a37fe)
![6](https://github.com/user-attachments/assets/c414442a-8ad0-41b4-b778-4180bf92681e)

**Comment by tai-jing-jian** [comment]
图片发你邮箱

**Comment by tai-jing-jian** [comment]
太镜鉴
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PlayerMiller109/obsidian-sheets-basic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月16日(星期三) 中午1:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PlayerMiller109/obsidian-sheets-basic] 阅读模式下，表格中的图像无法显示 (Issue #2)





 
Win11 v1.6.7 沙箱未复现。请沙箱测试排查是否存在插件主题 CSS 冲突、附必要截图及源码模式文本（用代码块格式包裹）。

**Comment by PlayerMiller109** [comment]
你好，你的截图在我这边是裂的。

<img width="200" src="https://github.com/user-attachments/assets/54c9c123-bba6-439f-b3c6-0ebb4f5df718">

另外我没太明白发邮箱指的是什么，我这边收到的是乱码。

另外沙箱测试和只开一个插件测试还是有区别的，尤其是如果你是只是关掉了其他插件没有重启或者卸载。如果不清楚请参考 [故障排查指导 Troubleshooting Guide](https://forum-zh.obsidian.md/t/topic/27879/1)。

**Comment by tai-jing-jian** [comment]
算了，你那没问题就行，我用原版那个插件，就没有这问题

**Comment by tai-jing-jian** [comment]
找到问题了 
![image-20241016152704112.png](images/未命名/image-20241016152704112.png) 这个样式，就会有这个问题
![[images/未命名/image-20241016152704112.png]] 这种，就不会

**Comment by tai-jing-jian** [comment]
找到问题了
`![image-20241016152704112.png](images/未命名/image-20241016152704112.png)` 这个样式，就会有这个问题
`![[images/未命名/image-20241016152704112.png]]` 这种，就不会

**Comment by PlayerMiller109** [comment]
没事的，你不用再 Reopen，也是可以继续 Comment 和 Edit 的。

<img width="200" src="https://github.com/user-attachments/assets/2730e153-a3bd-4aa6-8f36-c57abd4e55c6">
<img width="200" src="https://github.com/user-attachments/assets/3223b080-c304-416f-9aba-c866afd127cb"><br>

然后你之前说的发邮件，我之前是以为你知道一些我不会的操作，现在想来你是不是只是直接通过邮箱回复了？现在在这里 Comment 的你的 notification (通知) 和我的 no reply (请勿回复) 这两个账号呢不是私人邮箱的，所以你是不能这样发送文件的。看你应该是第一天用 GitHub 嘛。

<img width="650" src="https://github.com/user-attachments/assets/e1f0cd46-4a78-4aae-98a0-ee833471f471"><br>

另外你反映的这个问题我复现了，并且原版插件也存在这个问题。我可能得想想怎么修、能不能修。一段时间后再回复你。

以下为测试文本：

```markdown
|                    |     |
| ------------------ | --- |
| ![\|200](test.png) | <   |
| ![[test.png\|200]] |     |
```

**Comment by PlayerMiller109** [comment]
@tai-jing-jian 已修已测。请删除旧版本重启一遍 Ob 再下载新版本启用。

<img width="200" src="https://github.com/user-attachments/assets/d53899ab-d37b-484c-aa88-9eb6a3135268">

测试文本：

```markdown
|                                                                                 |     |
| ------------------------------------------------------------------------------- | --- |
| 左 ![image-20241016152704112.png\|100](images/未命名/image-20241016152704112.png) 右 | <   |
```

**Comment by tai-jing-jian** [comment]
又有新问题了，现在`![[images/未命名/image-20241016152704112.png]]` 这种出问题了

**Comment by PlayerMiller109** [comment]
之前光测了前后有文字的混排 Wiki 链接，没测着单独 Wiki 链接。现在再看下呢。

<img width="200" src="https://github.com/user-attachments/assets/cff0c3a8-362f-40c8-8357-3874d359e45f"><br>

测试文本：

```markdown
|                                                                                 |     |
| ------------------------------------------------------------------------------- | --- |
| 左 ![image-20241016152704112.png\|100](images/未命名/image-20241016152704112.png) 右 | <   |
| ![[images/未命名/image-20241016152704112.png\|100]]                            | <   |
```

**Comment by tai-jing-jian** [comment]
没问题了，厉害
